from __future__ import annotations

from pantry_pilot.models import Recipe, RecipeIngredient


def sample_recipes() -> tuple[Recipe, ...]:
    return (
        Recipe(
            title="Overnight Oats Bowl",
            cuisine="american",
            base_servings=2,
            prep_time_minutes=10,
            meal_types=("breakfast",),
            diet_tags=frozenset({"vegetarian"}),
            allergens=frozenset({"dairy"}),
            ingredients=(
                RecipeIngredient("rolled oats", 2.0, "cup"),
                RecipeIngredient("milk", 2.0, "cup"),
                RecipeIngredient("banana", 2.0, "item"),
                RecipeIngredient("peanut butter", 4.0, "tbsp"),
                RecipeIngredient("cinnamon", 1.0, "tsp"),
            ),
            steps=(
                "Stir oats, milk, peanut butter, and cinnamon together.",
                "Top with sliced banana and chill overnight.",
            ),
        ),
        Recipe(
            title="Berry Yogurt Parfait",
            cuisine="american",
            base_servings=2,
            prep_time_minutes=8,
            meal_types=("breakfast",),
            diet_tags=frozenset({"vegetarian"}),
            allergens=frozenset({"dairy"}),
            ingredients=(
                RecipeIngredient("yogurt", 2.0, "cup"),
                RecipeIngredient("frozen berries", 2.0, "cup"),
                RecipeIngredient("granola", 1.5, "cup"),
                RecipeIngredient("honey", 2.0, "tbsp"),
            ),
            steps=(
                "Layer yogurt, berries, and granola into bowls.",
                "Drizzle with honey before serving.",
            ),
        ),
        Recipe(
            title="Veggie Egg Scramble",
            cuisine="american",
            base_servings=2,
            prep_time_minutes=15,
            meal_types=("breakfast",),
            diet_tags=frozenset({"vegetarian", "gluten-free"}),
            allergens=frozenset({"egg"}),
            ingredients=(
                RecipeIngredient("eggs", 6.0, "item"),
                RecipeIngredient("spinach", 2.0, "cup"),
                RecipeIngredient("bell pepper", 1.0, "item"),
                RecipeIngredient("onion", 0.5, "item"),
                RecipeIngredient("cheddar cheese", 1.0, "cup"),
            ),
            steps=(
                "Saute chopped vegetables until tender.",
                "Add beaten eggs and cook until set, then fold in cheese.",
            ),
        ),
        Recipe(
            title="Cinnamon Banana Oatmeal",
            cuisine="american",
            base_servings=2,
            prep_time_minutes=12,
            meal_types=("breakfast",),
            diet_tags=frozenset({"vegan", "gluten-free"}),
            allergens=frozenset(),
            ingredients=(
                RecipeIngredient("rolled oats", 2.0, "cup"),
                RecipeIngredient("banana", 2.0, "item"),
                RecipeIngredient("cinnamon", 1.0, "tsp"),
                RecipeIngredient("honey", 1.0, "tbsp"),
            ),
            steps=(
                "Cook oats with water until creamy.",
                "Top with sliced banana, cinnamon, and honey.",
            ),
        ),
        Recipe(
            title="Tomato Avocado Toast",
            cuisine="american",
            base_servings=2,
            prep_time_minutes=10,
            meal_types=("breakfast", "lunch"),
            diet_tags=frozenset({"vegan"}),
            allergens=frozenset({"gluten"}),
            ingredients=(
                RecipeIngredient("bread", 4.0, "slice"),
                RecipeIngredient("avocado", 2.0, "item"),
                RecipeIngredient("tomato", 2.0, "item"),
                RecipeIngredient("lemon", 1.0, "item"),
            ),
            steps=(
                "Toast bread and mash avocado with lemon.",
                "Top with sliced tomato and serve immediately.",
            ),
        ),
        Recipe(
            title="Greek Chickpea Salad",
            cuisine="mediterranean",
            base_servings=4,
            prep_time_minutes=15,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegetarian", "gluten-free"}),
            allergens=frozenset({"dairy"}),
            ingredients=(
                RecipeIngredient("chickpeas", 2.0, "can"),
                RecipeIngredient("cucumber", 1.0, "item"),
                RecipeIngredient("tomato", 2.0, "item"),
                RecipeIngredient("feta", 1.0, "cup"),
                RecipeIngredient("olive oil", 4.0, "tbsp"),
                RecipeIngredient("lemon", 1.0, "item"),
            ),
            steps=(
                "Mix chickpeas with chopped vegetables and feta.",
                "Dress with olive oil and lemon juice.",
            ),
        ),
        Recipe(
            title="Lentil Tomato Soup",
            cuisine="mediterranean",
            base_servings=4,
            prep_time_minutes=30,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegan", "gluten-free"}),
            allergens=frozenset(),
            ingredients=(
                RecipeIngredient("lentils", 2.0, "cup"),
                RecipeIngredient("canned tomatoes", 2.0, "can"),
                RecipeIngredient("carrot", 2.0, "item"),
                RecipeIngredient("celery", 2.0, "stalk"),
                RecipeIngredient("onion", 1.0, "item"),
                RecipeIngredient("vegetable broth", 6.0, "cup"),
                RecipeIngredient("olive oil", 2.0, "tbsp"),
            ),
            steps=(
                "Cook onion, carrot, and celery in olive oil until softened.",
                "Add lentils, tomatoes, and broth, then simmer until tender.",
            ),
        ),
        Recipe(
            title="Black Bean Taco Bowls",
            cuisine="mexican",
            base_servings=4,
            prep_time_minutes=25,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegetarian", "gluten-free"}),
            allergens=frozenset(),
            ingredients=(
                RecipeIngredient("rice", 2.0, "cup"),
                RecipeIngredient("black beans", 2.0, "can"),
                RecipeIngredient("corn", 2.0, "cup"),
                RecipeIngredient("salsa", 1.5, "cup"),
                RecipeIngredient("avocado", 2.0, "item"),
                RecipeIngredient("lime", 1.0, "item"),
            ),
            steps=(
                "Cook rice and warm black beans with corn.",
                "Serve in bowls with salsa, avocado, and lime.",
            ),
        ),
        Recipe(
            title="Mediterranean Rice Bowl",
            cuisine="mediterranean",
            base_servings=4,
            prep_time_minutes=25,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegan", "gluten-free"}),
            allergens=frozenset(),
            ingredients=(
                RecipeIngredient("rice", 2.0, "cup"),
                RecipeIngredient("chickpeas", 2.0, "can"),
                RecipeIngredient("cucumber", 1.0, "item"),
                RecipeIngredient("tomato", 2.0, "item"),
                RecipeIngredient("lemon", 1.0, "item"),
                RecipeIngredient("olive oil", 2.0, "tbsp"),
            ),
            steps=(
                "Cook rice and warm chickpeas.",
                "Top bowls with cucumber, tomato, lemon, and olive oil.",
            ),
        ),
        Recipe(
            title="Garlic Tomato Pasta",
            cuisine="italian",
            base_servings=4,
            prep_time_minutes=25,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegan"}),
            allergens=frozenset({"gluten"}),
            ingredients=(
                RecipeIngredient("pasta", 16.0, "oz"),
                RecipeIngredient("canned tomatoes", 2.0, "can"),
                RecipeIngredient("spinach", 2.0, "cup"),
                RecipeIngredient("garlic", 4.0, "clove"),
                RecipeIngredient("olive oil", 2.0, "tbsp"),
            ),
            steps=(
                "Cook pasta until tender.",
                "Simmer tomatoes, garlic, and spinach, then toss with pasta.",
            ),
        ),
        Recipe(
            title="Tofu Stir-Fry",
            cuisine="asian",
            base_servings=4,
            prep_time_minutes=25,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegan"}),
            allergens=frozenset({"soy"}),
            ingredients=(
                RecipeIngredient("tofu", 2.0, "block"),
                RecipeIngredient("rice", 2.0, "cup"),
                RecipeIngredient("broccoli", 2.0, "cup"),
                RecipeIngredient("carrot", 2.0, "item"),
                RecipeIngredient("soy sauce", 4.0, "tbsp"),
                RecipeIngredient("garlic", 4.0, "clove"),
            ),
            steps=(
                "Cook rice while stir-frying tofu and vegetables.",
                "Add soy sauce and garlic, then cook until glossy.",
            ),
        ),
        Recipe(
            title="Pasta Primavera",
            cuisine="italian",
            base_servings=4,
            prep_time_minutes=30,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegetarian"}),
            allergens=frozenset({"gluten", "dairy"}),
            ingredients=(
                RecipeIngredient("pasta", 16.0, "oz"),
                RecipeIngredient("zucchini", 2.0, "item"),
                RecipeIngredient("bell pepper", 1.0, "item"),
                RecipeIngredient("spinach", 3.0, "cup"),
                RecipeIngredient("parmesan", 1.0, "cup"),
                RecipeIngredient("olive oil", 3.0, "tbsp"),
            ),
            steps=(
                "Cook pasta until tender.",
                "Saute vegetables and toss with pasta, olive oil, and parmesan.",
            ),
        ),
        Recipe(
            title="Chicken Rice Skillet",
            cuisine="american",
            base_servings=4,
            prep_time_minutes=35,
            meal_types=("dinner",),
            diet_tags=frozenset({"high-protein", "gluten-free"}),
            allergens=frozenset(),
            ingredients=(
                RecipeIngredient("chicken breast", 1.5, "lb"),
                RecipeIngredient("rice", 2.0, "cup"),
                RecipeIngredient("broccoli", 2.0, "cup"),
                RecipeIngredient("carrot", 2.0, "item"),
                RecipeIngredient("vegetable broth", 4.0, "cup"),
            ),
            steps=(
                "Brown chicken pieces in a skillet.",
                "Add rice, vegetables, and broth, then cover until cooked through.",
            ),
        ),
        Recipe(
            title="Turkey Chili",
            cuisine="american",
            base_servings=4,
            prep_time_minutes=40,
            meal_types=("dinner",),
            diet_tags=frozenset({"high-protein", "gluten-free"}),
            allergens=frozenset(),
            ingredients=(
                RecipeIngredient("ground turkey", 1.0, "lb"),
                RecipeIngredient("black beans", 2.0, "can"),
                RecipeIngredient("canned tomatoes", 2.0, "can"),
                RecipeIngredient("onion", 1.0, "item"),
                RecipeIngredient("bell pepper", 1.0, "item"),
                RecipeIngredient("chili powder", 2.0, "tbsp"),
            ),
            steps=(
                "Brown turkey with onion and bell pepper.",
                "Add beans, tomatoes, and chili powder, then simmer until thick.",
            ),
        ),
        Recipe(
            title="Chickpea Salsa Rice Skillet",
            cuisine="mexican",
            base_servings=4,
            prep_time_minutes=20,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegan", "gluten-free"}),
            allergens=frozenset(),
            ingredients=(
                RecipeIngredient("rice", 2.0, "cup"),
                RecipeIngredient("chickpeas", 2.0, "can"),
                RecipeIngredient("corn", 2.0, "cup"),
                RecipeIngredient("salsa", 1.5, "cup"),
                RecipeIngredient("bell pepper", 1.0, "item"),
            ),
            steps=(
                "Cook rice and saute bell pepper until tender.",
                "Fold in chickpeas, corn, and salsa until heated through.",
            ),
        ),
        Recipe(
            title="Broccoli Cheddar Rice Bowl",
            cuisine="american",
            base_servings=4,
            prep_time_minutes=25,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegetarian", "gluten-free"}),
            allergens=frozenset({"dairy"}),
            ingredients=(
                RecipeIngredient("rice", 2.0, "cup"),
                RecipeIngredient("broccoli", 3.0, "cup"),
                RecipeIngredient("cheddar cheese", 1.5, "cup"),
                RecipeIngredient("carrot", 2.0, "item"),
                RecipeIngredient("vegetable broth", 3.0, "cup"),
            ),
            steps=(
                "Cook rice with broth while steaming broccoli and carrot.",
                "Stir in cheddar until melted and serve in bowls.",
            ),
        ),
        Recipe(
            title="Peanut Noodles",
            cuisine="asian",
            base_servings=4,
            prep_time_minutes=20,
            meal_types=("lunch", "dinner"),
            diet_tags=frozenset({"vegetarian"}),
            allergens=frozenset({"gluten", "peanut", "soy"}),
            ingredients=(
                RecipeIngredient("pasta", 12.0, "oz"),
                RecipeIngredient("peanut butter", 6.0, "tbsp"),
                RecipeIngredient("soy sauce", 4.0, "tbsp"),
                RecipeIngredient("cucumber", 1.0, "item"),
                RecipeIngredient("carrot", 2.0, "item"),
            ),
            steps=(
                "Cook noodles and whisk together peanut butter and soy sauce.",
                "Toss noodles with sauce and vegetables.",
            ),
        ),
        Recipe(
            title="Mystery Curry",
            cuisine="indian",
            base_servings=4,
            prep_time_minutes=30,
            meal_types=("dinner",),
            diet_tags=frozenset({"vegetarian"}),
            allergens=None,
            ingredients=(
                RecipeIngredient("chickpeas", 2.0, "can"),
                RecipeIngredient("coconut milk", 2.0, "can"),
                RecipeIngredient("curry powder", 2.0, "tbsp"),
                RecipeIngredient("rice", 2.0, "cup"),
            ),
            steps=(
                "Simmer chickpeas with coconut milk and curry powder.",
                "Serve over rice.",
            ),
        ),
        Recipe(
            title="Avocado Toast",
            cuisine="american",
            base_servings=2,
            prep_time_minutes=10,
            meal_types=("breakfast", "lunch"),
            diet_tags=frozenset({"vegan"}),
            allergens=frozenset({"gluten"}),
            ingredients=(
                RecipeIngredient("bread", 4.0, "slice"),
                RecipeIngredient("avocado", 2.0, "item"),
                RecipeIngredient("tomato", 1.0, "item"),
                RecipeIngredient("olive oil", 1.0, "tbsp"),
            ),
            steps=(
                "Toast bread and mash avocado.",
                "Top toast with avocado, tomato, and olive oil.",
            ),
        ),
    )
